### ISSUE TITLE
Global store

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#19]
It'd be nice for the store to be in `~/.pnpm/store`.

The store is currently defined here:

https://github.com/rstacruz/pnpm/blob/20df53b3193d0b548a21d7287e0f9af3b62f8143/bin/pnpm-install#L93

But I'd like to have some features here:

- use [rc](https://www.npmjs.com/package/rc) to store this path in `.pnpmrc`
- Probably want to use [homedir](https://www.npmjs.com/package/home-dir) (or similar) to resolve `~`'s
- [relSymlink()](https://github.com/rstacruz/pnpm/blob/master/lib/rel_symlink.js) is currently being used to make symlinks from `.store/xxx@1.0.0` => `xxx`, automatically figuring out the relative path to do so. However, it should be amended such that if the store path is NOT inside the package dir (ie, it's in home), the symlink will be absolute, not relative
- ...whatever edge cases I haven't thought of

**Comment by rstacruz** [comment]
damn... not that easy. just realized there's some painful edge cases here... too sleepy to explain at the moment.

**Comment by rstacruz** [comment]
Okay, let me try to explain. imagine `pg-then` requires `pg`, and they're not bundled together. They'll be set up like this:

- `/project/node_modules/.store/pg-then@2.4.1`
- `/project/node_modules/.store/pg@1.5.0`
- `/project/node_modules/pg-then` (symlink)
- `/project/node_modules/pg` (symlink)

If, within `/project`, you do `require('pg-then')`, Node.js will read `./node_modules/pg-then`, which resolves to the one in the store.

Keep in mind `require.resolve('pg-then')` actually gives you the "real" path of `/project/node_modules/.store/pg-then@2.4.1/index.js`.

`pg-then` will now use `require('pg')` within itself, and this *will* work. The reason why this will work is because Node.js will search these paths:

- `/project/node_modules/.store/pg-then@2.4.1/node_modules/pg`
- `/project/node_modules/.store/node_modules/pg`
- `/project/node_modules/node_modules/pg`
- `/project/node_modules/pg` (found in here)
- `/node_modules/pg`

If we move `.store` into, say, `home/me/.pnpm/store`, this lookup path now becomes:

- `/home/me/.pnpm/store/pg-then@2.4.1/node_modules/pg`
- `/home/me/.pnpm/store/node_modules/pg`
- `/home/me/.pnpm/node_modules/pg`
- `/home/me/node_modules/pg`
- `/home/node_modules/pg`
- `/node_modules/pg`

As you can see, the project (`/project`) is no longer in the search path. Bummer.

**Comment by chrismcv** [comment]
what about the path to the store being `~/.pnpm/store/node_modules`?

**Comment by rstacruz** [comment]
In that case, require('lodash') won't work then--it needs to be
require('lodash@4.0.0'). It'd also be weird to be able to require packages
not in your project.

**Comment by rstacruz** [comment]
Considering it seems impossible, I'm closing this for now.

**Comment by dmitriz** [comment]
What about using `npm`'s native `link`ing?

If `pg` and `pg-then` are both installed into `home/.store` and 
`npm link ../pg` is run inside the `pg-then`-directory, then `pg` becomes accessible.

The only annoying downside is the pollution of the global installation space but maybe there is a way to customise away that global directory with some prefix magic?

**Comment by rstacruz** [comment]
Good try, but that's not entirely workable. For instance, if you want to store `babel` globally and have it used on your projects, it won't be able to see your projects's `babel-preset-es2015` package because that resides in a different node_modules path.

**Comment by dmitriz** [comment]
I don't quite understand. If I have a directory `babel-core` with exact copy of the original package and another one for `babel-preset-es2015`, wouldn't that `npm link ...` command make one module accessible from the other? It works for my local modules. Is `babel-core` different?

**Comment by rstacruz** [comment]
Assuming your global store is in `~/.store` (for simplicity's sake), you'll have these directories:

- `~/.store/babel-core`
- `/projects/xyz/node_modules/babel-preset-es2015`
- `/projects/xyz/node_modules/babel-core` *(symlink to ~/.store/babel-core)*

Now imagine `babel-core`'s `index.js` performs this call:

```js
/* from babel-core/index.js */
require('babel-preset-es2015')
```

The way this resolves for modules is it will start from the *canonical path* of babel-core, that is, `~/.store/babel-core`, and find the node_modules paths that are valid for that path. That is:

- `~/.store/babel-core/node_modules/babel-preset-es2015`
- `~/.store/node_modules/babel-preset-es2015`
- `~/node_modules/babel-preset-es2015`
- (and so on)

Since it resolves from the canonical path of `babel-core`, symlinking (or `npm link`ing, which is merely symlinking) your `babel-core` around your system won't let it see the node_modules in those symlinked paths.

**Comment by rstacruz** [comment]
Related: https://github.com/npm/npm/issues/5875

**Comment by dmitriz** [comment]
I see. Thanks for the explanation!

Another idea: 

Instead of direct symlinks, create "shell wrappers" that would change the context for the resolver. So in the local user directory I have the shell wrappers:
```sh
/projects/xyz/node_modules/babel-preset-es2015
/projects/xyz/node_modules/babel-core
```
So now I run locally `babel-core`, which is just the shell that in turn runs the actual symlink to the global `babel-core` but with additional context to tell the Node resolver to look under the local `/node_modules`. This way it would go again through the local shell-symlink-chain and would do the trick.

I understand that changing resolver context like that is possible in Webpack, so perhaps also in Node?

**Comment by rstacruz** [comment]
I'd be very interested to see if it's possible in Node.js :)

**Comment by alexeyten** [comment]
@dmitriz there will be problems with including inner files. Probably most common example would be `require('react-dom/server')` that will not be resolved properly.

**Comment by Meroje** [comment]
The issue you mentioned earlier is getting a fix on node 6 https://github.com/nodejs/node/pull/5950

**Comment by zkochan** [comment]
@Meroje I tried that new --preserve-symlinks option in node v6.3.0. I've changed the shebang of eslint in a shared pnpm store to `#!/usr/bin/node --preserve-symlinks`. However, the deps were being resolved to the original location as before. Maybe it works only when executed directly via the node command?!

**Comment by zkochan** [comment]
I've managed to make it work in node v6.3.0!!! :sunglasses: 

Steps (on Linux):

1. create a monorepo with subpackages
2. create a shared store for the subpackages
3. install eslint and some plugins to one of the packages
4. replace the eslint symlink in /node_modules/.bin with a real file that has this content:
  ```js
  #!/usr/bin/node --preserve-symlinks

  require('../eslint/bin/eslint')
  ```
5. make the file an executable with this command ` chmod 755 node_modules/.bin/eslint`

After these steps eslint finds its plugins without any problems even though the storage is in a different place!

**Comment by zkochan** [comment]
I think this issue can be reopened now that https://github.com/rstacruz/pnpm/issues/244 has been merged and it works on new NodeJS

The one thing that has to be done for a global store is the deletion of packages that are not used anymore.

**Comment by vjpr** [comment]
@zkochan I am having an issue the `preserve-symlink` proxy file.

When using `create-react-app`:

```
Error: Cannot find module '../react-scripts/bin/react-scripts.js'
```

**node_modules/react-scripts/bin/react-scripts.js**

```
#!/bin/sh
":" //# comment; exec /usr/bin/env node --preserve-symlinks "$0" "$@"
require('../react-scripts/bin/react-scripts.js')
```

This looks like a bug. The `bin` dir shouldn't be touched, only the top-level `.bin`.

**Comment by zkochan** [comment]
@vjpr please create an issue for this because now I can't look into it and I will most probably forget about this message :smile:

**Comment by foisonocean** [comment]
@rstacruz @zkochan 
Hi guys, I'm using Node v10.9.0 and pnpm 2.13.5 on mac OS X 10.11, and I try to install create-react-app by `pnpm install -g create-react-app`, then when I run `which create-react-app` I still get nothing.
Any suggestions for me?
